# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "review-and-recommend"
client_id = "719d051c89168a8fca5449a95ca9a949"
application_url = "https://4f84-2405-4802-1bf6-d0f0-ac53-5ae3-5ced-8f56.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = [
  "https://4f84-2405-4802-1bf6-d0f0-ac53-5ae3-5ced-8f56.ngrok-free.app/auth/callback",
  "https://4f84-2405-4802-1bf6-d0f0-ac53-5ae3-5ced-8f56.ngrok-free.app/auth/shopify/callback",
  "https://4f84-2405-4802-1bf6-d0f0-ac53-5ae3-5ced-8f56.ngrok-free.app/api/auth/callback",
  "https://4f84-2405-4802-1bf6-d0f0-ac53-5ae3-5ced-8f56.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "books-ecommere.myshopify.com"
