# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "review-and-recommend"
client_id = "719d051c89168a8fca5449a95ca9a949"
application_url = "https://opportunities-naval-interim-nevertheless.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = [
  "https://opportunities-naval-interim-nevertheless.trycloudflare.com/auth/callback",
  "https://opportunities-naval-interim-nevertheless.trycloudflare.com/auth/shopify/callback",
  "https://opportunities-naval-interim-nevertheless.trycloudflare.com/api/auth/callback",
  "https://opportunities-naval-interim-nevertheless.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "books-ecommere.myshopify.com"
